const ServiceActionTypes = {
    LOG_COLLECTION_TRIGGER_START: 'LOG_COLLECTION_TRIGGER_START',
    LOG_COLLECTION_TRIGGER_SUCCESS: 'LOG_COLLECTION_TRIGGER_SUCCESS',
    LOG_COLLECTION_TRIGGER_FAILURE: 'LOG_COLLECTION_TRIGGER_FAILURE',
    LOG_COLLECTION_STOP: 'LOG_COLLECTION_STOP',
    LOG_COLLECTION_RESET: 'LOG_COLLECTION_RESET'
}

export default ServiceActionTypes;